name: e_wallet
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.0-85.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  sqflite: 2.0.1
  font_awesome_flutter: 9.2.0
  google_fonts: 2.1.1
  get_storage: 2.0.3
  intl: 0.17.0
  month_picker_dialog: 0.4.0
  flex_color_picker: 2.2.0
  path_provider: 2.0.8
  package_info_plus: 1.3.0
  image_picker: 0.8.4+4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

